Projeto Calendario de Vacinacao/Controllers/GerenciaUsuariosController.cs
using Projeto_Calendario_de_Vacinacao.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto_Calendario_de_Vacinacao.Controllers
{
    public class GerenciaUsuariosController : Controller
    {        
        private ApplicationDbContext context;
        public GerenciaUsuariosController()
        {
            context = new ApplicationDbContext();
        }
        public ActionResult UsuariosComPerfils()
        {
            var usuariosComPerfis = (from user in context.Users
                                     select new
                                     {
                                         UserId = user.Id,
                                         Username = user.UserName,
                                         Email = user.Email,
                                         RoleNames = (from userRole in user.Roles
                                                      join role in context.Roles on userRole.RoleId
                                                      equals role.Id
                                                      select role.Name).ToList()
                                     }).ToList().Select(p => new UsersInRoleViewModel()
                                     {
                                         UserId = p.UserId,
                                         Username = p.Username,
                                         Email = p.Email,
                                         Role = string.Join(",", p.RoleNames)
                                     });
            return View(usuariosComPerfis);
        }
    }
}

Projeto Calendario de Vacinacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projeto Calendario de Vacinação ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/public/plugins/datatables/dataTables.bootstrap.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Criar Perfil", "Index", "Role")</li>
                    <li>@Html.ActionLink("Ver Usuários e Perfis", "UsuariosComPerfils", "GerenciaUsuarios")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Projeto Calendario de Vacinação ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/public/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/public/plugins/datatables/dataTables.bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Projeto Calendario de Vacinacao/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Bem-Vindo ao Calendario de Vacinação Infantil!</title>
    <!-- Bootstrap core CSS -->
    <link href=@Url.Content("~/Content/vendor/bootstrap/css/bootstrap.min.css") rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href=@Url.Content("~/Content/vendor/font-awesome/css/font-awesome.min.css") rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    @*<link href=@Url.Content("~/Content/css/grayscale.min.css") rel="stylesheet">*@
    <link href=@Url.Content("~/Content/css/grayscale.css") rel="stylesheet" />
    <link rel="stylesheet" href=@Url.Content("~/public/plugins/datatables/dataTables.bootstrap.css")>
</head>
<body id="page-top">
    @RenderBody()

    @*Map Section
        <div id="map"></div>*@

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Meu Projeto Calendario de Vacinação 2018</p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src=@Url.Content("~/Content/vendor/jquery/jquery.min.js")></script>
    <script src=@Url.Content("~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js")></script>
    <!-- Plugin JavaScript -->
    <script src=@Url.Content("~/Content/vendor/jquery-easing/jquery.easing.min.js")></script>
    @*Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>*@
    <!-- Custom scripts for this template -->
    <script src=@Url.Content("~/Content/js/grayscale.min.js")></script>
    <script src=@Url.Content("~/public/plugins/datatables/jquery.dataTables.min.js")></script>
    <script src=@Url.Content("~/public/plugins/datatables/dataTables.bootstrap.min.js")></script>
    @RenderSection("scripts", required: false)





</body>
</html>